[project]
name = "trading-model"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "ccxt>=4.4.78",
    "datasets>=3.5.0",
    "einops>=0.8.1",
    "gym>=0.26.2",
    "numpy>=2.2.5",
    "plotly>=6.0.1",
    "stable-baselines3>=2.6.0",
    "statsmodels>=0.14.4",
    "tensorboard>=2.19.0",
    "torch>=2.7.0",
]

[dependency-groups]
lint = ["pyright>=1.1.397", "ruff>=0.11.0"]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
