[project]
name = "trading-model"
version = "0.1.0"
requires-python = "==3.13.3"
dependencies = [
    "ccxt>=4.4.78",
    "datasets>=3.5.0",
    "einops>=0.8.1",
    "numpy>=2.2.5",
    "plotly>=6.0.1",
    "ta>=0.11.0",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
    "transformers>=4.51.3",
    "triton>=3.3.0",
]

[dependency-groups]
lint = ["pyright>=1.1.397", "ruff>=0.11.0"]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
