[project]
name = "trading-model"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "accelerate>=1.6.0",
    "ccxt>=4.4.78",
    "datasets>=3.5.0",
    "diffusers>=0.33.1",
    "einops>=0.8.1",
    "gguf>=0.16.3",
    "gguf-connector>=1.5.6",
    "gradio>=5.29.0",
    "numpy>=2.2.5",
    "plotly>=6.0.1",
    "tensorboard>=2.19.0",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]

[dependency-groups]
lint = ["pyright>=1.1.397", "ruff>=0.11.0"]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
